// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvP8nSExK5ooqIeSfs-mzUgAi7k0r-Xcs',
    appId: '1:214359255447:web:33261462ddd0a7f8d4bcd2',
    messagingSenderId: '214359255447',
    projectId: 'crudfireflutter-8568c',
    authDomain: 'crudfireflutter-8568c.firebaseapp.com',
    storageBucket: 'crudfireflutter-8568c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcz8I6cOneHWgLHXoKy0LmcaM2Kd2gNQ',
    appId: '1:214359255447:android:41402837e113fefcd4bcd2',
    messagingSenderId: '214359255447',
    projectId: 'crudfireflutter-8568c',
    storageBucket: 'crudfireflutter-8568c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GRdBiw7i3aYHdIKBYrTtO45FpnGbtJM',
    appId: '1:214359255447:ios:51dfa1e4feec2038d4bcd2',
    messagingSenderId: '214359255447',
    projectId: 'crudfireflutter-8568c',
    storageBucket: 'crudfireflutter-8568c.appspot.com',
    iosClientId: '214359255447-ns6n8o4sk0jblulid7bn3m0u2qhjdpcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-GRdBiw7i3aYHdIKBYrTtO45FpnGbtJM',
    appId: '1:214359255447:ios:51dfa1e4feec2038d4bcd2',
    messagingSenderId: '214359255447',
    projectId: 'crudfireflutter-8568c',
    storageBucket: 'crudfireflutter-8568c.appspot.com',
    iosClientId: '214359255447-ns6n8o4sk0jblulid7bn3m0u2qhjdpcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );
}
